name: Build Plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Find Plugin Jar File
        id: find-jar
        run: |
          jar_file=$(find target -type f -name "*.jar" -not -name "original-*.jar" | head -n 1)
          echo "::set-output name=jar_file::$jar_file"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Playstyle-Plugin
          path: ${{ steps.find-jar.outputs.jar_file }}